databases:
  - name: smartscheduler_db
    databaseName: smartscheduler_db
    user: db_user
    plan: free

services:
  - type: web
    name: backend
    env: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
      - key: DB_HOST
        fromDatabase:
          name: smartscheduler_db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: smartscheduler_db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: smartscheduler_db
          property: database
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: smartscheduler_db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: smartscheduler_db
          property: password
      - key: PORT
        value: 8080

  - type: web
    name: app-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: ${backend.url}
