spring.application.name=backend
server.port=${PORT:8080}

# Dynamic Database URL configuration for Render / Docker / Local
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:smartscheduler_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# JPA / Hibernate Settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false


# JWT Configuration
app.jwt.secret=SmartSchedulerPlusEnterpriseSecretKeyForJwtAuthenticationSecuritySystem2026!
app.jwt.expiration-ms=86400000

# Actuator Configuration
management.endpoints.web.exposure.include=health,info,metrics
management.endpoint.health.show-details=always
management.health.mail.enabled=false


# OpenAPI Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Spring Mail Configuration (Environment Driven - Real Gmail Dispatch)
spring.mail.host=${SPRING_MAIL_HOST:smtp.gmail.com}
spring.mail.port=${SPRING_MAIL_PORT:587}
spring.mail.username=${SPRING_MAIL_USERNAME:n.udaykumar2005@gmail.com}
spring.mail.password=${SPRING_MAIL_PASSWORD:ninpgitexztnqthl}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true



