spring.application.name=backend
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:smartscheduler_db}?createDatabaseIfNotExist=true
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:mysql}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
